apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-observability-svc
  labels:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: aggregator-dpg
    app.kubernetes.io/name: aggregator-dpg
    app.kubernetes.io/component: observability-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: aggregator-dpg
    app.kubernetes.io/component: observability-svc
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
