apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "worker.appConfigMap" . }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
data:
  SCHEMA_ROOT_DIR: "/app/config/schemas"
  BULK_MAX_ROWS: "{{ .Values.bulk.maxRows }}"
  BULK_MAX_ROW_BYTES: "{{ .Values.bulk.maxRowBytes }}"
  LINK_METRICS_ROLLUP_INTERVAL_MS: "{{ .Values.cron.linkMetricsRollupIntervalMs }}"
  WATCHDOG_INTERVAL_MS: "{{ .Values.cron.watchdogIntervalMs }}"
  S3_FORCE_PATH_STYLE: "{{ .Values.global.s3.forcePathStyle }}"
