/**
 * Scaffolds a new service package from packages/_template.
 *
 * Usage:
 *   pnpm new-service <name>
 *
 * Where <name> is the package slug (e.g. "signal-stack").
 * Creates packages/<name>/ with all template files, substituting
 * @aggregator-dpg/_template → @aggregator-dpg/<name> throughout.
 *
 * Aborts if packages/<name> already exists.
 */

import { execSync } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const TEMPLATE_DIR = 'packages/_template';
const PACKAGES_DIR = 'packages';

// Skipped at copy-time — regenerated by pnpm install
const SKIP = new Set(['node_modules', 'dist']);

function usage(): never {
  console.error('Usage: pnpm new-service <name>');
  console.error('Example: pnpm new-service signal-stack');
  process.exit(1);
}

function slug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

function copyDir(src: string, dest: string, name: string): void {
  mkdirSync(dest, { recursive: true });

  for (const entry of readdirSync(src)) {
    if (SKIP.has(entry)) continue;

    const srcPath = join(src, entry);
    const destPath = join(dest, entry);
    const stat = statSync(srcPath);

    if (stat.isDirectory()) {
      copyDir(srcPath, destPath, name);
    } else {
      const original = readFileSync(srcPath, 'utf8');
      const replaced = original
        .replaceAll('@aggregator-dpg/_template', `@aggregator-dpg/${name}`)
        .replaceAll('_template', name);
      writeFileSync(destPath, replaced, 'utf8');
    }
  }
}

function main(): void {
  const [, , rawName] = process.argv;

  if (!rawName) usage();

  const name = slug(rawName);

  if (!name) {
    console.error(`Invalid package name: "${rawName}"`);
    process.exit(1);
  }

  const repoRoot = process.cwd();
  const templatePath = join(repoRoot, TEMPLATE_DIR);
  const destPath = join(repoRoot, PACKAGES_DIR, name);

  if (!existsSync(templatePath)) {
    console.error(`Template not found at ${relative(repoRoot, templatePath)}`);
    process.exit(1);
  }

  if (existsSync(destPath)) {
    console.error(`Package already exists: ${relative(repoRoot, destPath)}`);
    console.error('Remove it manually first if you want to regenerate.');
    process.exit(1);
  }

  console.log(`Creating packages/${name} from template...`);
  copyDir(templatePath, destPath, name);

  console.log('Running pnpm install to link workspace...');
  execSync('pnpm install', { stdio: 'inherit', cwd: repoRoot });

  console.log(`\nDone. Next steps:`);
  console.log(`  1. Edit packages/${name}/src/interface.ts — define your abstract class`);
  console.log(`  2. Edit packages/${name}/src/in-memory/ — implement the in-memory fake`);
  console.log(`  3. Edit packages/${name}/src/testing/  — add seed helpers`);
  console.log(`  4. Edit packages/${name}/config.defaults.yaml — add config keys`);
  console.log(`  5. Run: pnpm --filter @aggregator-dpg/${name} test`);
}

main();
