/**
 * Guided-tour definitions for the aggregator (coordinator) portal.
 *
 * A tour is plain data: an ordered list of steps, each pointing at a
 * `[data-tour="…"]` anchor (or none, for a centred card). Keeping tours as
 * data — not code — lets the same shape later be hand-written, generated by an
 * AI from the portal's knowledge base, or served by an API, while the player
 * in `run-tour.ts` stays unchanged.
 *
 * Steps whose anchor is not on screen are skipped (or, with `keep`, shown as a
 * centred card), so a tour copes with empty states and config-gated controls.
 * Every tour is capped at five steps: related controls share a step and its
 * text lists them.
 *
 * Copy is English-only for now, like the Signals-DPG tours this mirrors.
 */
export interface GuideStep {
  /**
   * Element to highlight. A list is tried in order and the first one on screen
   * wins. Omit for a centred card.
   */
  element?: string | string[];
  /**
   * Show the step as a centred card when none of its elements are on screen,
   * instead of skipping it. For steps whose text matters on its own.
   */
  keep?: boolean;
  title: string;
  description: string;
}

export interface GuideTour {
  id: string;
  /** Shown in the help menu. */
  title: string;
  /** Route the tour starts on; the menu navigates here first if needed. */
  path: string;
  /** Whether this tour belongs to the page at `pathname`. */
  matches: (pathname: string) => boolean;
  /** Play once, automatically, on a first visit to a matching page. */
  autoStart?: boolean;
  steps: GuideStep[];
}

const PORTAL_TOUR: GuideTour = {
  id: 'portal',
  title: 'Get around the portal',
  path: '/dashboard',
  // The side panel and top bar are on every page.
  matches: () => true,
  autoStart: true,
  steps: [
    {
      element: '[data-tour="sidebar-nav"]',
      keep: true,
      title: 'Welcome 👋',
      description: `This portal is where you bring participants onto the network and follow how they are doing. The side panel takes you to:
        <ul>
          <li><b>Onboarding</b>: add participants by CSV, link or QR code.</li>
          <li><b>Profile</b>: your organisation's details.</li>
          <li><b>My …</b> (dashboard): every participant you onboarded, with their status.</li>
        </ul>`,
    },
    {
      element: '[data-tour="preferences"]',
      title: 'Language and theme',
      description: 'Switch the portal language, or between light and dark mode.',
    },
    {
      element: '[data-tour="support"]',
      title: 'Contact support',
      description:
        'Raise a complaint or a support request. Add details and attachments; the team replies to the email or phone you give.',
    },
    {
      element: '[data-tour="account"]',
      title: 'Your account',
      description:
        'Shows the organisation you are signed in for. Use the icon on the right to sign out.',
    },
    {
      element: '[data-tour="guide-button"]',
      keep: true,
      title: 'Help is always here',
      description:
        'Open this menu any time for a tour of the page you are on, or to learn how to do something else.',
    },
  ],
};

const DASHBOARD_TOUR: GuideTour = {
  id: 'dashboard',
  title: 'Track your participants',
  path: '/dashboard',
  matches: (p) => p === '/dashboard',
  steps: [
    {
      element: '[data-tour="dash-summary"]',
      keep: true,
      title: 'Your network at a glance',
      description: `
        <ul>
          <li>The total number of participants you have onboarded.</li>
          <li><b>Refresh</b> reloads the latest numbers.</li>
          <li><b>Add Participants</b> (top right) takes you to Onboarding.</li>
        </ul>`,
    },
    {
      element: '[data-tour="dash-status"]',
      title: 'Activity status',
      description: `
        <ul>
          <li><b>New</b>: recently joined.</li>
          <li><b>Active</b>: recently active on the network.</li>
          <li><b>At Risk</b>: activity is slowing down; worth a follow-up.</li>
          <li><b>Inactive</b>: no recent activity.</li>
        </ul>`,
    },
    {
      element: '[data-tour="dash-metrics"]',
      title: 'Profiles and users',
      description:
        'Profile health (for example how many profiles are complete) and user numbers (for example average profiles per user) across everyone you onboarded.',
    },
    {
      element: ['[data-tour="dash-search"]', '[data-tour="dash-table"]'],
      title: 'Find participants',
      description: `
        <ul>
          <li><b>Search</b> by name, ID or profile details.</li>
          <li><b>Lifecycle</b>: Draft (profile not finished) or Live (on the network).</li>
          <li><b>Filters</b>: narrow by activity status.</li>
        </ul>`,
    },
    {
      element: ['[data-tour="dash-rows"]', '[data-tour="dash-table"]'],
      keep: true,
      title: 'The participant table',
      description: `Each row is one participant: when they joined, profile status, requests initiated and received, and activity status.
        <ul>
          <li>Tick rows to <b>Export selected CSV</b> or <b>Export profile data</b>; tick the header box to select the page, then <b>Select all … matching</b> for every result.</li>
          <li>Use the page numbers at the bottom to move through the list.</li>
        </ul>`,
    },
  ],
};

const ONBOARDING_TOUR: GuideTour = {
  id: 'onboarding',
  title: 'Add participants',
  path: '/onboarding',
  matches: (p) => p === '/onboarding',
  steps: [
    {
      element: '[data-tour="onb-metrics"]',
      keep: true,
      title: 'Onboarding so far',
      description: `
        <ul>
          <li><b>Total submissions</b>, <b>Verified &amp; onboarded</b>, <b>Failed validations</b> and <b>Skipped</b>, across all methods.</li>
          <li><b>Joins by entry mode</b> splits them by CSV upload, registration link and QR code.</li>
        </ul>`,
    },
    {
      element: '[data-tour="onb-bulk"]',
      title: 'Bulk upload (CSV)',
      description: `The fastest way to add a large list you already have.
        <ul>
          <li>Files uploaded, rows, passed and failed.</li>
          <li><b>Recent uploads</b>: when an upload has failed rows, download <b>errors.csv</b> to see what to fix.</li>
          <li><b>Go to Bulk Upload</b> to add a file.</li>
        </ul>`,
    },
    {
      element: '[data-tour="onb-links"]',
      title: 'Registration links and QR codes',
      description:
        'Share a public link or QR code and participants register themselves. Shows your links, active links, registrations and how many are verified. <b>Create new link</b> to start one.',
    },
    {
      element: ['[data-tour="link-card"]', '[data-tour="onb-links"]'],
      keep: true,
      title: 'Managing a link',
      description: `
        <ul>
          <li><b>Draft</b>: not public yet. <b>Edit</b> the details, then <b>Make Live</b>.</li>
          <li><b>Live</b>: <b>Copy link</b>, <b>View QR</b> (and download it to print), <b>Open link</b>, or <b>Deactivate</b> to stop new registrations.</li>
        </ul>`,
    },
  ],
};

const BULK_UPLOAD_TOUR: GuideTour = {
  id: 'bulk-upload',
  title: 'Upload a CSV',
  path: '/onboarding/bulk-uploads',
  matches: (p) => p === '/onboarding/bulk-uploads',
  steps: [
    {
      element: ['[data-tour="csv-template"]', '[data-tour="csv-type"]'],
      keep: true,
      title: 'Start from the template',
      description:
        'The participant type is set by your organisation. <b>Download Excel template</b>, fill one participant per row, and save it as CSV.',
    },
    {
      element: '[data-tour="csv-dropzone"]',
      title: 'Add your file',
      description:
        'Drag the CSV here, or click to browse. Picked the wrong one? Remove it and choose again.',
    },
    {
      element: '[data-tour="csv-attest"]',
      title: 'Confirm permission',
      description:
        'Tick to confirm you have the participants’ permission to register them. Upload stays disabled until you do.',
    },
    {
      element: '[data-tour="csv-upload"]',
      title: 'Upload',
      description:
        'Rows are checked and accounts are created. You are taken back to Onboarding, where <b>Recent uploads</b> shows passed and failed rows; download <b>errors.csv</b> to fix any failures and upload those rows again.',
    },
  ],
};

const LINKS_TOUR: GuideTour = {
  id: 'links',
  title: 'Create a registration link',
  path: '/onboarding/links',
  matches: (p) => p === '/onboarding/links',
  steps: [
    {
      element: '[data-tour="link-form"]',
      keep: true,
      title: 'Describe the event',
      description:
        'Your organisation and domain are filled in for you. Add the <b>State</b>, <b>Event</b> and <b>District</b> (required), and optionally the date, location and tags, so you can tell registrations from different events apart.',
    },
    {
      element: '[data-tour="link-mode"]',
      title: 'Campaign type',
      description:
        'How participants will register through this link, for example <b>Form Filling</b> or <b>Voice Campaign</b>.',
    },
    {
      element: '[data-tour="link-create"]',
      title: 'Create the link',
      description:
        'If anything is missing, the list above the button says what. The link is created as a <b>Draft</b> and you are taken to Onboarding.',
    },
    {
      title: 'Make it live',
      description:
        'On Onboarding, find the draft under <b>Your Registration Links</b> and click <b>Make Live</b>. Its public link and QR code then appear, ready to share or print.',
    },
  ],
};

const PROFILE_TOUR: GuideTour = {
  id: 'profile',
  title: 'Your organisation profile',
  path: '/profile',
  matches: (p) => p === '/profile',
  steps: [
    {
      element: '[data-tour="profile-details"]',
      keep: true,
      title: 'Aggregator details',
      description:
        'The details your organisation registered with. They are read-only here so they stay consistent across the network.',
    },
    {
      element: '[data-tour="profile-request"]',
      title: 'Request an update',
      description:
        'Need something changed? Choose the fields that can be updated, enter the new values next to the current ones, and submit the request.',
    },
  ],
};

const PROFILE_COMPLETE_TOUR: GuideTour = {
  id: 'profile-complete',
  title: 'Complete your profile',
  path: '/profile/complete',
  matches: (p) => p === '/profile/complete',
  steps: [
    {
      element: '[data-tour="profile-complete-form"]',
      keep: true,
      title: 'Complete your profile',
      description:
        'Fill in the remaining details about your organisation. Required fields are marked.',
    },
    {
      element: '[data-tour="profile-save"]',
      title: 'Save',
      description:
        'Becomes active once the form is valid. A confirmation appears when it is saved.',
    },
  ],
};

export const TOURS: GuideTour[] = [
  PORTAL_TOUR,
  DASHBOARD_TOUR,
  ONBOARDING_TOUR,
  BULK_UPLOAD_TOUR,
  LINKS_TOUR,
  PROFILE_TOUR,
  PROFILE_COMPLETE_TOUR,
];

export function findTour(id: string): GuideTour | undefined {
  return TOURS.find((t) => t.id === id);
}
